export enum UserRole {
  DOCENT_ASSISTANT = 'DOCENT_ASSISTANT',
  COORDINATOR = 'COORDINATOR',
  ADMIN = 'ADMIN'
}

export enum Course {
  ADS = 'ADS',
  GE = 'GE',
  GTI = 'GTI',
  GEMP = 'GEMP',
  MEC = 'MEC'
}

export enum Semester {
  SEM1 = 'SEM1',
  SEM2 = 'SEM2',
  SEM3 = 'SEM3',
  SEM4 = 'SEM4',
  SEM5 = 'SEM5',
  SEM6 = 'SEM6'
}

export enum Location {
  AUDITORIO = 'AUDITORIO',
  BIBLIOTECA = 'BIBLIOTECA',
  SALA_MAKER = 'SALA_MAKER',
  LAB_MECANICA_METROLOGIA = 'LAB_MECANICA_METROLOGIA',
  LAB_SISTEMAS_INTEGRADOS = 'LAB_SISTEMAS_INTEGRADOS',
  LAB_HIDRAULICA_PNEUMATICA = 'LAB_HIDRAULICA_PNEUMATICA',
  LAB_ENSAIOS_METALOGRAFICOS = 'LAB_ENSAIOS_METALOGRAFICOS',
  LAB_ELETRONICA_POTENCIA = 'LAB_ELETRONICA_POTENCIA',
  LAB_COMANDOS_ELETRICOS = 'LAB_COMANDOS_ELETRICOS',
  LAB_CONTROLE_PROCESSOS = 'LAB_CONTROLE_PROCESSOS',
  LAB_INFORMATICA_1 = 'LAB_INFORMATICA_1',
  LAB_INFORMATICA_2 = 'LAB_INFORMATICA_2',
  LAB_INFORMATICA_3 = 'LAB_INFORMATICA_3',
  LAB_INFORMATICA_4 = 'LAB_INFORMATICA_4',
  LAB_INFORMATICA_5 = 'LAB_INFORMATICA_5',
  LAB_INFORMATICA_6 = 'LAB_INFORMATICA_6',
  SALA_1 = 'SALA_1',
  SALA_2 = 'SALA_2',
  SALA_3 = 'SALA_3',
  SALA_4 = 'SALA_4',
  SALA_5 = 'SALA_5',
  SALA_6 = 'SALA_6',
  SALA_7 = 'SALA_7',
  SALA_8 = 'SALA_8',
  SALA_9 = 'SALA_9',
  SALA_9_3_4 = 'SALA_9_3_4',
  SALA_10 = 'SALA_10',
  SALA_11 = 'SALA_11',
  SALA_12 = 'SALA_12',
  OUTROS = 'OUTROS'
}

export enum Category {
  PALESTRA = 'PALESTRA',
  WORKSHOP = 'WORKSHOP',
  OFICINA = 'OFICINA',
  CURSO = 'CURSO',
  VISITA_TECNICA = 'VISITA_TECNICA'
}
